server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jbp?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    # ????????:true-???????false-??
    check-process-definitions: false
    #??????????
#   process-definition-location-prefix: classpath:/processes/
#   process-definition-location-suffixes:
#      - **.bpmn
#      - **.bpmn20.xml


